sudo: false

langauge: python

python:
  - 3.7

install:
  - pip install -r ./Software/requirements.txt

branches:
  only:
    - master

script:
  - coverage run ./Software/PiKwonDo/PiKwonDoTest.py

after_success:
  - codecov
